/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lecturer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String surname;
    private String email;
    private String phone;

    public Lecturer() {}

    public Lecturer(Lecturer value) {
        this.id = value.id;
        this.name = value.name;
        this.surname = value.surname;
        this.email = value.email;
        this.phone = value.phone;
    }

    public Lecturer(
        Long   id,
        String name,
        String surname,
        String email,
        String phone
    ) {
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.phone = phone;
    }

    /**
     * Getter for <code>public.lecturer.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.lecturer.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.lecturer.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.lecturer.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.lecturer.surname</code>.
     */
    public String getSurname() {
        return this.surname;
    }

    /**
     * Setter for <code>public.lecturer.surname</code>.
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Getter for <code>public.lecturer.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.lecturer.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.lecturer.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.lecturer.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lecturer (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
