/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subject implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private String  name;
    private String  code;
    private Integer hourCount;

    public Subject() {}

    public Subject(Subject value) {
        this.id = value.id;
        this.name = value.name;
        this.code = value.code;
        this.hourCount = value.hourCount;
    }

    public Subject(
        Long    id,
        String  name,
        String  code,
        Integer hourCount
    ) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.hourCount = hourCount;
    }

    /**
     * Getter for <code>public.subject.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.subject.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.subject.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.subject.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.subject.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>public.subject.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>public.subject.hour_count</code>.
     */
    public Integer getHourCount() {
        return this.hourCount;
    }

    /**
     * Setter for <code>public.subject.hour_count</code>.
     */
    public void setHourCount(Integer hourCount) {
        this.hourCount = hourCount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subject (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(hourCount);

        sb.append(")");
        return sb.toString();
    }
}
