/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Timetable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer roomNumber;
    private Integer pareNumber;
    private Long lectureId;
    private Long subjectId;

    public Timetable() {
    }

    public Timetable(Timetable value) {
        this.id = value.id;
        this.roomNumber = value.roomNumber;
        this.pareNumber = value.pareNumber;
        this.lectureId = value.lectureId;
        this.subjectId = value.subjectId;
    }

    public Timetable(
            Long id,
            Integer roomNumber,
            Integer pareNumber,
            Long lectureId,
            Long subjectId
    ) {
        this.id = id;
        this.roomNumber = roomNumber;
        this.pareNumber = pareNumber;
        this.lectureId = lectureId;
        this.subjectId = subjectId;
    }

    /**
     * Getter for <code>public.timetable.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.timetable.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.timetable.room_number</code>.
     */
    public Integer getRoomNumber() {
        return this.roomNumber;
    }

    /**
     * Setter for <code>public.timetable.room_number</code>.
     */
    public void setRoomNumber(Integer roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * Getter for <code>public.timetable.pare_number</code>.
     */
    public Integer getPareNumber() {
        return this.pareNumber;
    }

    /**
     * Setter for <code>public.timetable.pare_number</code>.
     */
    public void setPareNumber(Integer pareNumber) {
        this.pareNumber = pareNumber;
    }

    /**
     * Getter for <code>public.timetable.lecture_id</code>.
     */
    public Long getLectureId() {
        return this.lectureId;
    }

    /**
     * Setter for <code>public.timetable.lecture_id</code>.
     */
    public void setLectureId(Long lectureId) {
        this.lectureId = lectureId;
    }

    /**
     * Getter for <code>public.timetable.subject_id</code>.
     */
    public Long getSubjectId() {
        return this.subjectId;
    }

    /**
     * Setter for <code>public.timetable.subject_id</code>.
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Timetable (");

        sb.append(id);
        sb.append(", ").append(roomNumber);
        sb.append(", ").append(pareNumber);
        sb.append(", ").append(lectureId);
        sb.append(", ").append(subjectId);

        sb.append(")");
        return sb.toString();
    }
}
