server:
  port: 8090

spring:
  application:
    name: Demo4Application
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  flyway:
    defaultSchema: public
    baselineOnMigrate: true
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      show-sql: false
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    org:
      jooq: DEBUG