/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Subject;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectRecord extends UpdatableRecordImpl<SubjectRecord> implements Record4<Long, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subject.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subject.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.subject.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subject.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.subject.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subject.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.subject.hour_count</code>.
     */
    public void setHourCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.subject.hour_count</code>.
     */
    public Integer getHourCount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Subject.SUBJECT.ID;
    }

    @Override
    public Field<String> field2() {
        return Subject.SUBJECT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Subject.SUBJECT.CODE;
    }

    @Override
    public Field<Integer> field4() {
        return Subject.SUBJECT.HOUR_COUNT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public Integer component4() {
        return getHourCount();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public Integer value4() {
        return getHourCount();
    }

    @Override
    public SubjectRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubjectRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public SubjectRecord value4(Integer value) {
        setHourCount(value);
        return this;
    }

    @Override
    public SubjectRecord values(Long value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectRecord
     */
    public SubjectRecord() {
        super(Subject.SUBJECT);
    }

    /**
     * Create a detached, initialised SubjectRecord
     */
    public SubjectRecord(Long id, String name, String code, Integer hourCount) {
        super(Subject.SUBJECT);

        setId(id);
        setName(name);
        setCode(code);
        setHourCount(hourCount);
    }

    /**
     * Create a detached, initialised SubjectRecord
     */
    public SubjectRecord(jooqdata.tables.pojos.Subject value) {
        super(Subject.SUBJECT);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCode(value.getCode());
            setHourCount(value.getHourCount());
        }
    }
}
