/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import jooqdata.Keys;
import jooqdata.Public;
import jooqdata.tables.records.SubjectRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subject extends TableImpl<SubjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.subject</code>
     */
    public static final Subject SUBJECT = new Subject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectRecord> getRecordType() {
        return SubjectRecord.class;
    }

    /**
     * The column <code>public.subject.id</code>.
     */
    public final TableField<SubjectRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.subject.name</code>.
     */
    public final TableField<SubjectRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.subject.code</code>.
     */
    public final TableField<SubjectRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.subject.hour_count</code>.
     */
    public final TableField<SubjectRecord, Integer> HOUR_COUNT = createField(DSL.name("hour_count"), SQLDataType.INTEGER.nullable(false), this, "");

    private Subject(Name alias, Table<SubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(String alias) {
        this(DSL.name(alias), SUBJECT);
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(Name alias) {
        this(alias, SUBJECT);
    }

    /**
     * Create a <code>public.subject</code> table reference
     */
    public Subject() {
        this(DSL.name("subject"), null);
    }

    public <O extends Record> Subject(Table<O> child, ForeignKey<O, SubjectRecord> key) {
        super(child, key, SUBJECT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SubjectRecord, Long> getIdentity() {
        return (Identity<SubjectRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SubjectRecord> getPrimaryKey() {
        return Keys.SUBJECT_PKEY;
    }

    @Override
    public Subject as(String alias) {
        return new Subject(DSL.name(alias), this);
    }

    @Override
    public Subject as(Name alias) {
        return new Subject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(String name) {
        return new Subject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(Name name) {
        return new Subject(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
