/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.daos;


import java.util.List;

import jooqdata.tables.Subject;
import jooqdata.tables.records.SubjectRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectDao extends DAOImpl<SubjectRecord, jooqdata.tables.pojos.Subject, Long> {

    /**
     * Create a new SubjectDao without any configuration
     */
    public SubjectDao() {
        super(Subject.SUBJECT, jooqdata.tables.pojos.Subject.class);
    }

    /**
     * Create a new SubjectDao with an attached configuration
     */
    public SubjectDao(Configuration configuration) {
        super(Subject.SUBJECT, jooqdata.tables.pojos.Subject.class, configuration);
    }

    @Override
    public Long getId(jooqdata.tables.pojos.Subject object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Subject.SUBJECT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchById(Long... values) {
        return fetch(Subject.SUBJECT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooqdata.tables.pojos.Subject fetchOneById(Long value) {
        return fetchOne(Subject.SUBJECT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Subject.SUBJECT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchByName(String... values) {
        return fetch(Subject.SUBJECT.NAME, values);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Subject.SUBJECT.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchByCode(String... values) {
        return fetch(Subject.SUBJECT.CODE, values);
    }

    /**
     * Fetch records that have <code>hour_count BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchRangeOfHourCount(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Subject.SUBJECT.HOUR_COUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>hour_count IN (values)</code>
     */
    public List<jooqdata.tables.pojos.Subject> fetchByHourCount(Integer... values) {
        return fetch(Subject.SUBJECT.HOUR_COUNT, values);
    }
}
