/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Lecturer;
import jooqdata.tables.Subject;
import jooqdata.tables.Timetable;
import jooqdata.tables.records.LecturerRecord;
import jooqdata.tables.records.SubjectRecord;
import jooqdata.tables.records.TimetableRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LecturerRecord> LECTURER_PKEY = Internal.createUniqueKey(Lecturer.LECTURER, DSL.name("lecturer_pkey"), new TableField[] { Lecturer.LECTURER.ID }, true);
    public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = Internal.createUniqueKey(Subject.SUBJECT, DSL.name("subject_pkey"), new TableField[] { Subject.SUBJECT.ID }, true);
    public static final UniqueKey<TimetableRecord> TIMETABLE_PKEY = Internal.createUniqueKey(Timetable.TIMETABLE, DSL.name("timetable_pkey"), new TableField[] { Timetable.TIMETABLE.ID }, true);
}
