/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Lecturer;
import jooqdata.tables.Subject;
import jooqdata.tables.Timetable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lecturer</code>.
     */
    public static final Lecturer LECTURER = Lecturer.LECTURER;

    /**
     * The table <code>public.subject</code>.
     */
    public static final Subject SUBJECT = Subject.SUBJECT;

    /**
     * The table <code>public.timetable</code>.
     */
    public static final Timetable TIMETABLE = Timetable.TIMETABLE;
}
